### PR TITLE
periodictable v1.7.1

### PR DESCRIPTION
**Pull request by mrakitin**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Reset the build number to `0` (if the version changed)
* [ ] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [ ] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by mrakitin** [comment]
@conda-forge-admin, please rerender

**Comment by mrakitin** [comment]
The [license](https://github.com/pkienzle/periodictable/blob/b36d7bf9def086c1e5a7a62d29e25d8e79f5a8f2/LICENSE.txt#L19-L28)'s text looks like `BSD-3-Clause`.

**Comment by bjodah** [comment]
It looks like most of it is public domain, and then a single file looks listed to be BSD-3-Clause?
https://github.com/pkienzle/periodictable/blob/master/LICENSE.txt

**Comment by bjodah** [comment]
Feel free to open a new PR to rectify if I've misunderstood the license attribution. Perhaps we should update the URL to the homepage as well, the link in meta.yaml is currently broken I think,

**Comment by mrakitin** [comment]
Thanks for merging, @bjodah! I'll check with the developers.

**Comment by mrakitin** [comment]
I hope we'll get the answer via https://github.com/pkienzle/periodictable/issues/85.

**Comment by pkienzle** [comment]
BSD-3-Clause

As @bjodah noted most of the code has no restrictions, but conda-forge will be distributing the whole package so needs to specify the most restrictive license.

**Pull request merged**
